DROP TABLE IF EXISTS [dbo].[BondReturns]

CREATE TABLE [dbo].[BondReturns](
	[Date] [date] NOT NULL,
    [IssueId] [int] NULL,
    [Cusip] [nvarchar](10) NOT NULL,
    [BondSymId] [nvarchar](20) NULL,
    [Bsym] [nvarchar](20) NULL,
    [Isin] [nvarchar](20) NULL,
    [CompanySymbol] [nvarchar](10) NULL,
    [BondType] [nvarchar](4) NULL,
    [SecurityLevel] [nvarchar](4) NULL,
    [Conv] [int] NULL,
    [OfferingDate] [date] NULL,
    [OfferingAmt] [float] NULL,
    [OfferingPrice] [float] NULL,
    [PrincipalAmt] [int] NULL,
    [Maturity] [date] NULL,
    [TreasuryMaturity] [nvarchar](20) NULL,
    [Coupon] [float] NULL,
    [DayCountBasis] [nvarchar](10) NULL,
    [DatedDate] [date] NULL,
    [FirstInterestDate] [date] NULL,
    [LastInterestDate] [date] NULL,
    [Ncoups] [int] NULL,
    [AmountOutstanding] [float] NULL,
    [RSp] [nvarchar](10) NULL,
    [RMr] [nvarchar](10) NULL,
    [RFr] [nvarchar](10) NULL,
    [NSp] [float] NULL,
    [NMr] [float] NULL,
    [NFr] [float] NULL,
    [RatingNum] [float] NULL,
    [RatingCat] [nvarchar](10) NULL,
    [RatingClass] [nvarchar](10) NULL,
    [TDate] [date] NULL,
    [TVolume] [bigint] NULL,
    [TDvolume] [bigint] NULL,
    [TSpread] [float] NULL, -- percent
    [TYldPt] [float] NULL,
    [Yield] [float] NULL, -- percent
    [PriceEom] [float] NULL,
    [PriceLdm] [float] NULL,
    [PriceL5m] [float] NULL,
    [Gap] [float] NULL,
    [CoupMonth] [float] NULL,
    [NextCoup] [date] NULL,
    [CoupAmt] [float] NULL,
    [CoupAcc] [float] NULL,
    [MultiCoups] [int] NULL,
    [RetEom] [float] NULL,
    [RetLdm] [float] NULL,
    [RetL5m] [float] NULL,
    [Tmt] [float] NULL,
    [RemCoups] [float] NULL,
    [Duration] [float] NULL,
    [Defaulted] [nvarchar](1) NULL,
    [DefaultDate] [date] NULL,
    [DefaultType] [nvarchar](1) NULL,
    [Reinstated] [nvarchar](1) NULL,
    [ReinstatedDate] [date] NULL,
	CONSTRAINT [PK_BondReturns] PRIMARY KEY CLUSTERED (
        [Cusip] ASC,
		[Date] ASC
	) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
