DROP TABLE IF EXISTS [dbo].[BondReturns]

CREATE TABLE [dbo].[BondReturns](
	[Date] [date] NOT NULL,
    [IssueId] [int] NULL,
    [Cusip] [nvarchar](10) NOT NULL,
    [BondSymId] [nvarchar](20) NULL,
    [Bsym] [nvarchar](20) NULL,
    [Isin] [nvarchar](20) NULL,
    [CompanySymbol] [nvarchar](10) NULL,
    [BondType] [nvarchar](4) NULL,
    [SecurityLevel] [nvarchar](4) NULL,
    [Conv] [int] NULL,
    [OfferingDate] [date] NULL,
    [OfferingAmt] [decimal] NULL,
    [OfferingPrice] [decimal] NULL,
    [PrincipalAmt] [int] NULL,
    [Maturity] [date] NULL,
    [TreasuryMaturity] [nvarchar](20) NULL,
    [Coupon] [decimal] NULL,
    [DayCountBasis] [nvarchar](10) NULL,
    [DatedDate] [date] NULL,
    [FirstInterestDate] [date] NULL,
    [LastInterestDate] [date] NULL,
    [Ncoups] [int] NULL,
    [AmountOutstanding] [decimal] NULL,
    [RSp] [nvarchar](10) NULL,
    [RMr] [nvarchar](10) NULL,
    [RFr] [nvarchar](10) NULL,
    [NSp] [decimal] NULL,
    [NMr] [decimal] NULL,
    [NFr] [decimal] NULL,
    [RatingNum] [decimal] NULL,
    [RatingCat] [nvarchar](10) NULL,
    [RatingClass] [nvarchar](10) NULL,
    [TDate] [date] NULL,
    [TVolume] [bigint] NULL,
    [TDvolume] [bigint] NULL,
    [TSpread] [decimal] NULL, -- percent
    [TYldPt] [decimal] NULL,
    [Yield] [decimal] NULL, -- percent
    [PriceEom] [decimal] NULL,
    [PriceLdm] [decimal] NULL,
    [PriceL5m] [decimal] NULL,
    [Gap] [decimal] NULL,
    [CoupMonth] [decimal] NULL,
    [NextCoup] [date] NULL,
    [CoupAmt] [decimal] NULL,
    [CoupAcc] [decimal] NULL,
    [MultiCoups] [int] NULL,
    [RetEom] [decimal] NULL,
    [RetLdm] [decimal] NULL,
    [RetL5m] [decimal] NULL,
    [Tmt] [decimal] NULL,
    [RemCoups] [decimal] NULL,
    [Duration] [decimal] NULL,
    [Defaulted] [nvarchar](1) NULL,
    [DefaultDate] [date] NULL,
    [DefaultType] [nvarchar](1) NULL,
    [Reinstated] [nvarchar](1) NULL,
    ReinstatedDate [date] NULL,
	CONSTRAINT [PK_BondReturns] PRIMARY KEY CLUSTERED (
        [Cusip] ASC,
		[Date] ASC
	) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
